FBFLAG_DOUBLE = 0x00000001
FBFLAG_VSYNC  = 0x00000002

FramebufferDesc.backbuffer = 0x00
FramebufferDesc.flags = 0x04

FramebufferInfo.w     = 0x00
FramebufferInfo.h     = 0x04
FramebufferInfo.vw    = 0x08
FramebufferInfo.vh    = 0x0C
FramebufferInfo.pitch = 0x10
FramebufferInfo.depth = 0x14
FramebufferInfo.x     = 0x18
FramebufferInfo.y     = 0x1C
FramebufferInfo.ptr   = 0x20
FramebufferInfo.size  = 0x24
